version: "3.7"

services:
  web:
    networks:
      - okami_services
    env_file:
      - .env
    build: .
    volumes:
      - ./:/app
    ports:
      - "5173:5173"

networks:
  okami_services:
    name: okami_services
